openapi: 3.0.0
info:
  title: Autoroute
  version: 0.1.0

security:
  - "auth:sanctum": []

paths:
  /login:
    post:
      operationId: SessionController@login
      security: []
      responses:
        "200":
          $ref: "#/components/responses/204"

  /users:
    post:
      security: []
      requestBody:
        $ref: "#/components/requestBodies/User"

      responses:
        "201":
          $ref: "#/components/responses/204"

    get:
      security: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  - $ref: "#/components/schemas/User"

  /users/{user_id}:
    parameters:
      - $ref: "#/components/parameters/user_id"
    put:
      security: []
      requestBody:
        description: User request body
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string

      responses:
        "200":
          $ref: "#/components/responses/204"

    get:
      security: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

  /users/{user_id}/posts:
    parameters:
      - $ref: "#/components/parameters/user_id"
    get:
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  - $ref: "#/components/schemas/Post"
    post:
      requestBody:
        $ref: "#/components/requestBodies/Post"
      responses:
        "201":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"

  /users/{user_id}/posts/{post_id}:
    parameters:
      - $ref: "#/components/parameters/user_id"
      - $ref: "#/components/parameters/post_id"
    put:
      requestBody:
        $ref: "#/components/requestBodies/Post"
    delete:
      responses:
        "204":
          description: Success
    get:
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  - $ref: "#/components/schemas/Post"
components:
  schemas:
    id:
      type: integer
      minimum: 1

    User:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/id"
        name:
          type: string
        email:
          type: string
          format: email

    Post:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/id"
        title:
          type: string
        description:
          type: string

  parameters:
    user_id:
      in: path
      name: user_id
      schema:
        $ref: "#/components/schemas/id"
      required: true
      description: User ID

    post_id:
      in: path
      name: post_id
      schema:
        $ref: "#/components/schemas/id"
      required: true
      description: Post ID

  requestBodies:
    Post:
      description: Post request body
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - title
            properties:
              title:
                type: string
                format: min:3

    User:
      description: User request body
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - name
              - email
              - password
            properties:
              name:
                type: string
              email:
                type: string
                format: email
              password:
                type: string
                format: min:8
              device_name:
                type: string
                format: "between:5,10"

  responses:
    "401":
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string

    "204":
      description: No Content

  securitySchemes:
    "auth:sanctum":
      type: http
      scheme: bearer
